apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  labels:
    app: html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>My HTML App</title>
      </head>
      <body>
        <h1>Hello from Argo CD!</h1>
        <p>This is a simple static HTML page deployed via GitOps.</p>
      </body>
    </html>
